Revert "Fix lock annotations"
This reverts commit 7ed0cbfc6291fa18ad5109d6c29bc1b1fbc8094a.

Reason for revert: 

../../lib/tonic/debugger/dart_debugger.cc:25:13: error: expecting
mutex 'monitor_.mutex_' to be held at start of each loop

Change-Id: I0b6a829005dd4be7eabf321397cdef442907e6cd